// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI assistant that scans new lead requests, identifies relevant keywords,
 * and recommends team members best suited to handle the request.
 *
 * - routeLead - A function that routes a lead based on the request content.
 * - RouteLeadInput - The input type for the routeLead function.
 * - RouteLeadOutput - The return type for the routeLead function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RouteLeadInputSchema = z.object({
  requestContent: z
    .string()
    .describe('The content of the lead request, including the services they are interested in.'),
});
export type RouteLeadInput = z.infer<typeof RouteLeadInputSchema>;

const RouteLeadOutputSchema = z.object({
  recommendedTeamMembers: z
    .array(z.string())
    .describe('An array of team member names who are best suited to handle the request.'),
  reasoning: z
    .string()
    .describe('The AI reasoning for recommending these team members.'),
});
export type RouteLeadOutput = z.infer<typeof RouteLeadOutputSchema>;

export async function routeLead(input: RouteLeadInput): Promise<RouteLeadOutput> {
  return routeLeadFlow(input);
}

const prompt = ai.definePrompt({
  name: 'routeLeadPrompt',
  input: {schema: RouteLeadInputSchema},
  output: {schema: RouteLeadOutputSchema},
  prompt: `You are an AI assistant responsible for routing new lead requests to the appropriate team members.

  Your task is to analyze the lead request content, identify the services required, and based on those services, recommend the most suitable team members.

  ## Team Members and Specializations:
  - John: Specializes in Facebook Ads and Google Ads.
  - Jane: Specializes in Google My Business (GMB) and SEO.
  - Alice: Specializes in Website Creation and Design.
  - Bob: Specializes in AI Automation and Chat Automation.

  ## Instructions:
  1.  Read the "Request Content" carefully.
  2.  Identify the key services the user is asking for (e.g., 'Facebook Ads', 'website creation').
  3.  Match the identified services to the team members' specializations.
  4.  Provide your response as a JSON object that strictly follows the output schema.
  5.  The 'recommendedTeamMembers' array should contain the names of the matched team members.
  6.  The 'reasoning' field should explain *why* you chose those team members based on the request.

  ## Request Content:
  {{{requestContent}}}
  `,
});

const routeLeadFlow = ai.defineFlow(
  {
    name: 'routeLeadFlow',
    inputSchema: RouteLeadInputSchema,
    outputSchema: RouteLeadOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
